language: scala

before_install:
  - sudo apt-get install python-numpy

before_script:
    - sbt script
    - source setupenv

scala:
    - 2.10.2
jdk:
    - oraclejdk7

notifications:
    email: hoanglenghiaduc@gmail.com
    irc: "chat.freenode.net#xcode-leon"
